# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3
      types: [python]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      language_version: python3
      types: [python]
